# Replace with your Discord Application ID
application_id: "1540240351053217802"

# Activity type: 0 = Playing, 1 = Streaming, 2 = Listening, 3 = Watching
type: 1

# Activity Details
name: "The Death of 7 Billion People"
details: "Killing 7 billion people"
state: "Kill them, kill them all~!"
startTimestamp: 1124582400000

# Activity Images
largeImageKey: "1540243369572311111"
largeImageText: "I am Niko from Blue Archive"
smallImageKey: "1540270635375267970"
smallImageText: "Fox 2, Ready for The Mission!"

# Activity URL (optional, works only with certain types)
url: "https://twitch.tv"

# Activity Buttons (optional)
buttons:
  - name: "Visit Website"
    url: "https://www.nexoscreator.tech"
  - name: "GitHub Repo"
    url: "https://github.com/nexoslabs/discord-24-7-rich-presence"

# Activity Custom status
custom_status: "Kill people with me."
custom_emoji: "🔫"
